apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devfest-gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ifeoluwashola/gitops.git
    targetRevision: gitops
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
